-- First-device reservations grant no account, certificate or sync authority.
grant context_relay_rls_owner to current_user with inherit false, set true;
grant create on schema public to context_relay_rls_owner;
set local role context_relay_rls_owner;
grant usage, create on schema context_relay_private to session_user;
reset role;

create table context_relay_private.enrollment_reservations (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  session_id uuid not null,
  reservation_id uuid not null,
  account_id uuid not null,
  workspace_id uuid not null,
  nonce bytea not null check (pg_catalog.octet_length(nonce) = 32),
  expires_at timestamptz not null,
  window_started_at timestamptz not null,
  request_count integer not null check (request_count between 1 and 6)
);
alter table context_relay_private.enrollment_reservations owner to context_relay_rls_owner;
alter table context_relay_private.enrollment_reservations enable row level security;
revoke all on table context_relay_private.enrollment_reservations from public, anon, authenticated, service_role;

set local role context_relay_rls_owner;
revoke all on schema context_relay_private from session_user;

-- IDs and nonce are generated by the trusted Edge service, never copied from
-- client ownership fields. The caller supplies its stable reservation operation ID.
create function public.service_reserve_enrollment_for_session(
  p_auth_user_id uuid, p_session_id uuid, p_reservation_id uuid,
  p_account_id uuid, p_workspace_id uuid, p_nonce bytea
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  reservation context_relay_private.enrollment_reservations%rowtype;
  checked_at timestamptz;
begin
  if p_auth_user_id is null or p_session_id is null
    or p_reservation_id is null or p_account_id is null or p_workspace_id is null
    or p_nonce is null or pg_catalog.octet_length(p_nonce) <> 32
    or p_reservation_id::text !~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    or p_account_id::text !~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    or p_workspace_id::text !~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  then raise exception using errcode = '22023', message = 'invalid_enrollment_request'; end if;

  if not context_relay_private.lock_live_account_lifecycle_auth_session(p_auth_user_id, p_session_id)
  then raise exception using errcode = '42501', message = 'enrollment_session_denied'; end if;

  insert into context_relay_private.enrollment_reservations
    (auth_user_id, session_id, reservation_id, account_id, workspace_id, nonce,
     expires_at, window_started_at, request_count)
  values (p_auth_user_id, p_session_id, p_reservation_id, p_account_id, p_workspace_id, p_nonce,
    pg_catalog.clock_timestamp() + interval '10 minutes', pg_catalog.clock_timestamp(), 1)
  on conflict (auth_user_id) do nothing;

  select * into strict reservation from context_relay_private.enrollment_reservations
  where auth_user_id = p_auth_user_id for update;
  -- Both INSERT conflict waits and the row lock may outlive the Auth session.
  if not context_relay_private.lock_live_account_lifecycle_auth_session(p_auth_user_id, p_session_id)
  then raise exception using errcode = '42501', message = 'enrollment_session_denied'; end if;
  checked_at := pg_catalog.clock_timestamp();
  if exists (select 1 from public.accounts where owner_user_id = p_auth_user_id)
  then raise exception using errcode = '42501', message = 'enrollment_requires_pairing'; end if;

  if reservation.reservation_id = p_reservation_id then
    if reservation.session_id <> p_session_id or reservation.expires_at <= checked_at
    then raise exception using errcode = '42501', message = 'enrollment_reservation_expired'; end if;
    -- Exact operation retry returns the original server-generated challenge.
  else
    if reservation.expires_at > checked_at
    then raise exception using errcode = '40001', message = 'enrollment_in_progress'; end if;
    if reservation.window_started_at + interval '1 hour' <= checked_at then
      reservation.window_started_at := checked_at;
      reservation.request_count := 0;
    end if;
    if reservation.request_count >= 6
    then raise exception using errcode = '54000', message = 'enrollment_rate_limited'; end if;
    update context_relay_private.enrollment_reservations set
      session_id = p_session_id, reservation_id = p_reservation_id,
      account_id = p_account_id, workspace_id = p_workspace_id, nonce = p_nonce,
      expires_at = checked_at + interval '10 minutes',
      window_started_at = reservation.window_started_at,
      request_count = reservation.request_count + 1
    where auth_user_id = p_auth_user_id returning * into reservation;
  end if;
  return pg_catalog.jsonb_build_object(
    'reservationId', reservation.reservation_id, 'accountId', reservation.account_id,
    'workspaceId', reservation.workspace_id, 'nonce', pg_catalog.encode(reservation.nonce, 'hex'),
    'expiresAt', pg_catalog.floor(extract(epoch from reservation.expires_at) * 1000)::text
  );
end;
$$;
revoke all on function public.service_reserve_enrollment_for_session(uuid, uuid, uuid, uuid, uuid, bytea)
from public, anon, authenticated, service_role;
grant execute on function public.service_reserve_enrollment_for_session(uuid, uuid, uuid, uuid, uuid, bytea)
to service_role;

reset role;
revoke create on schema public from context_relay_rls_owner;
revoke context_relay_rls_owner from current_user;
